<a href="https://colab.research.google.com/github/RituAnilkumar/nnrms/blob/main/Fundamentals_of_Python_Programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamentals of Python Programming

**Author:** Ritu Anilkumar | Scientist/Engineer SD

ritu.anilkumar@nesac.gov.in

## How do we work with Python?


1.   Download Python from https://www.python.org/, write script as .py file and execute
  *   Terminal/Powershell
  *   Use an IDE like IDLE, PyCharm, VS Code
  *   Use a notebook like Jupyter Notebook.

2.   Install Anaconda: install on different environments

3. Online platforms without installing Python: Eg Azure, Colab etc

# Comments, commands and datatypes
In this section, we will cover:

1.   Commands are run by the computer. Comments are ignored and meant for programmer for understanding.
2.   Some preliminary commands: print, type
3.   Basic data types: int, float, string


In [1]:
# The first command of any programming language: Hello world!
print('Hello World!')

Hello World!


In [2]:
# Printing a number
print(1)

1


In [3]:
# Common datatypes: int, string, float
print(type(1.0))
print(type(1))
print(type("1"))

<class 'float'>
<class 'int'>
<class 'str'>


# Variables
We use variables to store information. In the above example, we have printed "Hello World!" We can also save this in a variable and print it directly through the print command. This is useful when we need to use the same line multiple times.

In [4]:
x='Hello World!'
print(x)
print(x)
print(x)

Hello World!
Hello World!
Hello World!


In [5]:
print('x')

x


# Arithmetic Operations

Next, let's take a look at some simple operations. We will create variables a and b and pass values to it. We will print the sum of a and b.

In [6]:
a=3
b=9
c=a+b
d=a-b
print('The sum of a and b is ',c)
print('The difference of a and b is ',d)

The sum of a and b is  12
The difference of a and b is  -6


In [7]:
print(2**4)
2**2

16


4

# Relational Operations

Relational oeprations give an output of true or false

In [8]:
a=1
b=3
print('Is a greater than or equal to b:',a>=b)
print('Is a lesser than b:',(a<b))


Is a greater than or equal to b: False
Is a lesser than b: True


In [9]:
print(type(True))

<class 'bool'>


# Logical Operations

Applies AND, OR, NOT etc. Also Boolean output

In [10]:
a=1
b=3
c=1
print('Is a greater than b OR a not equal to c:',(a>b)|(a!=c))
print('Is a lesser than b AND a equal to c:',(a<b)&(a==c))

Is a greater than b OR a not equal to c: False
Is a lesser than b AND a equal to c: True


In [11]:
a=1
b=3
c=1

In [12]:
print(a>b)

False


In [13]:
print(a!=c)

False


In [14]:
print((a>b)|(a==c))

True


# Some more data types

## Lists

A list is a sequence of objects. It can have any number of objects inside. In Python lists are written with square brackets

In [15]:
tourist_locations = ['Double decker libing root bridge', 'Mawlyngbna watertrek', 'Dawki river', 'Krang Suri waterfall']
print(tourist_locations)

['Double decker libing root bridge', 'Mawlyngbna watertrek', 'Dawki river', 'Krang Suri waterfall']


Elements can be accessed by the index that starts with 0

In [16]:
print(tourist_locations[2])

Dawki river


We can also use negative indices to start from the last

In [17]:
print(tourist_locations[-2])

Dawki river


You can call len() function with any Python object and it will calculates the size of the object.

In [18]:
print(len(tourist_locations))

4


You can add elements to the list using the Python function append()

In [19]:
print('Old list:',tourist_locations)
tourist_locations.append('Wei Saw Dong waterfall')
print('New list:',tourist_locations)

Old list: ['Double decker libing root bridge', 'Mawlyngbna watertrek', 'Dawki river', 'Krang Suri waterfall']
New list: ['Double decker libing root bridge', 'Mawlyngbna watertrek', 'Dawki river', 'Krang Suri waterfall', 'Wei Saw Dong waterfall']


You can also include different datatypes in the same list

In [20]:
test=[1,2,'test']
print(test[-1])

test


**USEFUL TIP** : There is a helper function called range if you would like to create a list of numbers in a particular range. It includes the first element and skips the last element.

In [21]:
a=range(2,100)
print(a[0])
print(a[1])
# print(a[2])
# print(a[3])

2
3


In [22]:
len(a)

98

## Dictionaries

In Python dictionaries are written with curly brackets {}. Dictionaries have keys and values. With lists, we can access each element by its index. But a dictionary makes it easy to access the element by name. Keys and values are separated by a colon :.

In [23]:
data = {'location': 'Double decker living root bridge', 'weekly_tourists': 88}
print(data)

{'location': 'Double decker living root bridge', 'weekly_tourists': 88}


In [24]:
data['location']

'Double decker living root bridge'

# Functions

Sometimes, we have a set of operations which need to be repeated over and over again. In such cases, it's a good idea to define functions. Functions generally consist of the function name, it's arguments, the operations performed and the values returned. Consider the following example of a function:

In [25]:
def add_subtract(a,b):
  sum=a+b
  diff=a-b
  return sum,diff

**NOTE: Please see the indentation in the function.** Here, add_subtract is the function name which is defined using the def keyword. We pass the arguments a and b to the function and two variables for sum and difference are calculated and returned. Now, we can call the function and get the outputs.

In [26]:
x=5
y=2
s1,d1=add_subtract(x,y)
print('Sum1 is ',s1,' and difference1 is ',d1)

Sum1 is  7  and difference1 is  3


In [27]:
s2,d2=add_subtract(6,1)
print('Sum2 is ',s2,' and difference2 is ',d2)


Sum2 is  7  and difference2 is  5


In [28]:
print('Sum3 and difference3 is ', add_subtract(2,9))

Sum3 and difference3 is  (11, -7)


# Logic Flow with if statements

We also have some statements that will help us make decisions about what statements to execute next. These are the control statements. A commonly used such statement is the if else statement illustrated below:

In [29]:
def check_rel(a,b):
  if a>b:
    print(a,' is greater than', b)
  elif a<b:
    print(a,' is less than', b)
  else:
    print('The numbers ',a,' and ',b,' are equal')

In [30]:
check_rel(1,2)

1  is less than 2


We can have the user input a value of their choice as well. This is done using the input function. The input value is by default treated as a string. We can change the data type to be an integer by using type casting. Below, the in function performs the type casting where a string to converted to an integer.

In [31]:
print("Énter a number")
x=int(input("enter value"))

Énter a number
enter value4


In [32]:
check_rel(3,x)

3  is less than 4


In [33]:
check_rel(2,2)

The numbers  2  and  2  are equal


# Logic Flow with for statements

In case a set of statements are to be repeated as long as a condition is valid, we use loops. Consider an example of the for loop below. We can see that i is initially set to 0 and incremented by 1 after each iteration of the loop until it reaches 5. When it reaches 5, it no longer satisfies the condition and hence the execution stops

In [34]:
i=5
while i>0:
  print(i)
  i=i-1
print('completed')

5
4
3
2
1
completed


In [35]:
for i in [0,1,2]:
  print(i)
  print('Done')
print('Stop')

0
Done
1
Done
2
Done
Stop


# Introducing Libraries with Numpy

In order to do matrix operations, there is a commonly used library called numpy. This can be imported and we can explore some of the basics of numpy below.

In [36]:
import numpy
a=[1,2,3]
print(type(a))
b=numpy.array([1,2,3])
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


We can import libraries with an alias to reduce typing effort

In [37]:
import numpy as np
a=[1,2,3]
print(type(a))
b=np.array([1,2,3])
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


We can use several functions of numpy in Python. Some of them include the shape function, ones function, zeros function, arange function, reshape function etc.

In [38]:
def test(a,b):
  print(a)
  print(b)

In [39]:
test(1,2)

1
2


In [40]:
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [41]:
b=np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
a.shape

(3, 4)

In [43]:
b.shape

(3, 4)

Similar to the range function, numpy has the arange function

In [44]:
a=np.arange(0,31,2,int)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


Let's see the shape of a

In [45]:
a.shape

(16,)

Reshape function changes the shape to the required shape

In [46]:
b=a.reshape(4,4)
print(b)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]


In [47]:
print(b.shape)

(4, 4)


If you don't know the size exactly, use -1

In [48]:
c=a.reshape(4,-1)
print(c.shape)

(4, 4)


You can refer to the different elements of the numpy array using it's indices. The first row, first column is 0,0 and so on. If want to select a range of values, you can use the colon operator too.

In [49]:
print(b)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]


In [50]:
print(b[2:,2:])

[[20 22]
 [28 30]]


In [51]:
print(b)
print('Next')
print(b[0,1])
print('Next')
print(b[3,3])
print('Next')
print(b[:,0])
print('Next')
print(b[:2,:])

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]
Next
2
Next
30
Next
[ 0  8 16 24]
Next
[[ 0  2  4  6]
 [ 8 10 12 14]]


***